apiVersion: v1
kind: Service
metadata:
  name: imagineai-frontend
  namespace: imagineai
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: imagineai-frontend
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: imagineai-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: imagineai-frontend
