apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: imagineai

commonLabels:
  app.kubernetes.io/part-of: imagineai-platform
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - service-account.yaml
  - network-policy.yaml
  - ingress.yaml
  # FastAPI
  - fastapi/deployment.yaml
  - fastapi/service.yaml
  - fastapi/hpa.yaml
  # Django Admin
  - django/deployment.yaml
  - django/service.yaml
  # Celery Worker
  - celery-worker/deployment.yaml
  - celery-worker/hpa.yaml
  # Celery Beat
  - celery-beat/deployment.yaml
  # Frontend
  - frontend/deployment.yaml
  - frontend/service.yaml
