apiVersion: v1
kind: ServiceAccount
metadata:
  name: imagineai-sa
  namespace: imagineai
  labels:
    app.kubernetes.io/name: imagineai
    app.kubernetes.io/part-of: imagineai-platform
    app.kubernetes.io/managed-by: kustomize
  annotations:
    # IRSA â€” set via overlay per environment
    # eks.amazonaws.com/role-arn: arn:aws:iam::role/imagineai-api
automountServiceAccountToken: false
