apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: imagineai

resources:
  - ../../base

patches:
  - path: patches.yaml

configMapGenerator:
  - name: imagineai-config
    behavior: merge
    literals:
      - APP_ENV=development
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
      - FASTAPI_WORKERS=1
      - FASTAPI_RELOAD=true
      - DJANGO_DEBUG=true
      - CORS_ORIGINS=http://localhost:4200
      - DB_POOL_SIZE=5
      - DB_MAX_OVERFLOW=5
      - CELERY_WORKER_CONCURRENCY=2
