{{- if .Values.fastapi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "imagineai.fullname" . }}-fastapi
  labels:
    {{- include "imagineai.labels" . | nindent 4 }}
    {{- include "imagineai.selectorLabels" (dict "component" "fastapi" "root" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.fastapi.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "imagineai.selectorLabels" (dict "component" "fastapi" "root" .) | nindent 4 }}
{{- end }}
