{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "imagineai.fullname" . }}-fastapi
  labels:
    {{- include "imagineai.labels" . | nindent 4 }}
    {{- include "imagineai.selectorLabels" (dict "component" "fastapi" "root" .) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "imagineai.selectorLabels" (dict "component" "fastapi" "root" .) | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
