apiVersion: v1
kind: Service
metadata:
  name: imagineai-fastapi
  namespace: imagineai
  labels:
    app.kubernetes.io/name: fastapi
    app.kubernetes.io/instance: imagineai-fastapi
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: imagineai-platform
    app.kubernetes.io/managed-by: kustomize
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: fastapi
    app.kubernetes.io/instance: imagineai-fastapi
