apiVersion: v1
kind: Service
metadata:
  name: imagineai-django
  namespace: imagineai
  labels:
    app.kubernetes.io/name: django
    app.kubernetes.io/instance: imagineai-django
    app.kubernetes.io/component: admin
    app.kubernetes.io/part-of: imagineai-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: django
    app.kubernetes.io/instance: imagineai-django
